import archiver from 'archiver';
import { Readable } from 'stream';

/**
 * ZIP Exporter Service
 * Creates ZIP archives of generated games with playable HTML5 structure
 */

/**
 * Create a ZIP file from game files
 * @param {Object} gameData - Game data with files object
 * @param {Object} res - Express response object (optional, for streaming)
 * @returns {Promise<Buffer>} ZIP file buffer
 */
export async function createGameZip(gameData, res = null) {
  return new Promise((resolve, reject) => {
    // Create archiver instance
    const archive = archiver('zip', {
      zlib: { level: 9 } // Maximum compression
    });

    const chunks = [];

    // Handle archive events
    archive.on('error', (err) => {
      console.error('Archive error:', err);
      reject(err);
    });

    archive.on('warning', (err) => {
      if (err.code === 'ENOENT') {
        console.warn('Archive warning:', err);
      } else {
        reject(err);
      }
    });

    // If response object provided, pipe to response (streaming download)
    if (res) {
      archive.pipe(res);
    } else {
      // Otherwise, collect chunks to create buffer
      archive.on('data', (chunk) => chunks.push(chunk));
    }

    archive.on('end', () => {
      if (!res) {
        resolve(Buffer.concat(chunks));
      } else {
        resolve();
      }
    });

    // Add game files to archive
    if (gameData.files) {
      Object.entries(gameData.files).forEach(([filename, content]) => {
        archive.append(content, { name: filename });
      });
    }

    // Add metadata file
    const metadata = {
      name: gameData.metadata?.name || 'Generated Game',
      version: gameData.metadata?.version || '1.0.0',
      type: gameData.metadata?.type || 'game',
      created: gameData.metadata?.created || new Date().toISOString(),
      generator: 'GAMECHAMBER',
      apiUsed: gameData.apiUsed || 'unknown'
    };

    archive.append(JSON.stringify(metadata, null, 2), { name: 'metadata.json' });

    // Add launch instructions
    const launchInstructions = `# How to Play This Game

## Quick Start
1. Unzip this file to a folder on your computer
2. Open 'index.html' in a modern web browser (Chrome, Firefox, Safari, or Edge)
3. Start playing!

## Files Included
- index.html - Main game file (open this to play)
- style.css - Game styling
- game.js - Game logic and mechanics
- README.md - Game information and details
- metadata.json - Technical metadata

## Requirements
- Modern web browser with JavaScript enabled
- No internet connection required (runs offline)

## Controls
See README.md for specific game controls

## Troubleshooting
- Make sure JavaScript is enabled in your browser
- Try a different browser if the game doesn't load
- Clear browser cache if you see an old version

## Credits
Generated by GAMECHAMBER - AI-Powered Game Generation Platform
https://github.com/your-repo/gamechamber

Enjoy your game!
`;

    archive.append(launchInstructions, { name: 'HOW_TO_PLAY.txt' });

    // Finalize the archive
    archive.finalize();
  });
}

/**
 * Stream a game ZIP to HTTP response
 * @param {Object} gameData - Game data
 * @param {Object} res - Express response object
 * @param {String} filename - Download filename
 */
export async function streamGameZip(gameData, res, filename = 'game.zip') {
  try {
    // Set headers for download
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    // Create and stream ZIP
    await createGameZip(gameData, res);
  } catch (error) {
    console.error('Error streaming ZIP:', error);
    throw error;
  }
}

/**
 * Create ZIP buffer (for storing or further processing)
 * @param {Object} gameData - Game data
 * @returns {Promise<Buffer>} ZIP file buffer
 */
export async function createGameZipBuffer(gameData) {
  try {
    return await createGameZip(gameData, null);
  } catch (error) {
    console.error('Error creating ZIP buffer:', error);
    throw error;
  }
}

/**
 * Validate game data before creating ZIP
 * @param {Object} gameData - Game data to validate
 * @returns {Boolean} True if valid
 */
export function validateGameData(gameData) {
  if (!gameData) {
    return false;
  }

  if (!gameData.files || typeof gameData.files !== 'object') {
    return false;
  }

  // Check for required files
  const requiredFiles = ['index.html'];
  for (const file of requiredFiles) {
    if (!gameData.files[file]) {
      return false;
    }
  }

  return true;
}

/**
 * Get ZIP file size estimate
 * @param {Object} gameData - Game data
 * @returns {Number} Estimated size in bytes
 */
export function estimateZipSize(gameData) {
  let totalSize = 0;

  if (gameData.files) {
    Object.values(gameData.files).forEach(content => {
      totalSize += Buffer.byteLength(content, 'utf8');
    });
  }

  // Estimate ~60% compression ratio
  return Math.round(totalSize * 0.6);
}

export default {
  createGameZip,
  streamGameZip,
  createGameZipBuffer,
  validateGameData,
  estimateZipSize
};
